# Generated by Django 5.2.7 on 2026-01-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jatek',
            name='aknaszam',
        ),
    ]
